package net.yuanmomo.springboot.business.mybatis;

import java.util.List;
import net.yuanmomo.springboot.bean.ToDo;
import net.yuanmomo.springboot.bean.ToDoParam;
import net.yuanmomo.springboot.mybatis.mapper.todo.ToDoMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Isolation;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ToDoBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    private static Logger logger = LoggerFactory.getLogger(ToDoBusiness.class);

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    @Autowired
    private ToDoMapper toDoMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int insertSelective(ToDo obj) throws Exception {
        if(obj  == null ){
            return 0;
        }
        return this.toDoMapper.insertSelective(obj);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int insertSelective(List<ToDo> list) throws Exception {
        int insertCount = 0;
        if (list == null || list.size() == 0) {
            return insertCount;
        }
        for (ToDo  obj : list) {
            if (obj == null) {
                continue;
            }
            try {
                insertCount += this.toDoMapper.insertSelective(obj);
            } catch (Exception e) {
                throw e;
            }
        }
        return insertCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    public ToDo getToDoByKey(Long key) throws Exception {
        return this.toDoMapper.selectByPrimaryKey(key);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int update(ToDo obj) throws Exception {
        if(obj  == null ){
            return 0;
        }
        return this.toDoMapper.updateByPrimaryKeySelective(obj);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    @Transactional(propagation=Propagation.REQUIRED,isolation =Isolation.REPEATABLE_READ, rollbackFor = Exception.class)
    public int update(List<ToDo> list) throws Exception {
        int updateCount = 0;
        if (list == null || list.size() == 0) {
            return updateCount;
        }
        for (ToDo  obj : list) {
            if (obj == null || obj.getId() == null || obj.getId() <= 0 ) {
                continue;
            }
            try {
                updateCount += this.toDoMapper.updateByPrimaryKeySelective(obj);
            } catch (Exception e) {
                throw e;
            }
        }
        return updateCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    public List<ToDo> selectToDoList(ToDoParam param) throws Exception {
        return this.toDoMapper.selectByExample(param);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_to_do
     *
     * @mbg.generated
     */
    public long countToDoList(ToDoParam param) throws Exception {
        return this.toDoMapper.countByExample(param);
    }
}